config/routes.rb
Groups::Application.routes.draw do
  devise_for :users
  
   resources :groups do
    resources :membership_requests, :controller => "membership_requests" do
      member do
        post :accept
      end
    end
   end

  root :to => "groups#index"
  
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  has_many :group_admins, :dependent => :destroy
  has_many :membership_requests, :dependent => :destroy
end

app/models/group_admin.rb
class GroupAdmin < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/membership_request.rb
class MembershipRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
 
  has_many :memberships, :dependent => :destroy
  has_many :groups, :through => :memberships
  has_many :group_admins, :dependent => :destroy
  has_many :membership_requests, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

 before_filter :authenticate_user!
 before_filter :member?, :only => :show
 before_filter :admin?, :only => [:destroy, :edit]
 
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @owner = User.find_by_id(@group.owner_id)
    @requests = @group.membership_requests
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end


  def create
    @group = Group.new(params[:group])
    @group.owner_id = current_user.id
    @group.users << current_user
      if @group.save
        @group_admin = @group.group_admins.build(:user_id => current_user.id)
        @group_admin.save
        redirect_to(@group, :notice => 'Group was successfully created.')
      else
        render :action => "new"
      end
  end


  def update
    @group = Group.find(params[:id])
    respond_to do |format|
      if @group.update_attributes(params[:group])
       redirect_to(@group, :notice => 'Group was successfully updated.')
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to(groups_url)
  end
  
  def apply_to_group
    @group = Group.find(params[:id])
    Membership_request.create(:user_id => current_user.id, :group_id => @group.id)
    redirect_to groups_path
  end
  
 protected
  
  def member?
    @group = Group.find(params[:id])
    if !@group.users.include?(current_user) then
      redirect_to(groups_url :notice => 'You are not a member of this group.')
    end
  end
  
  def admin?
    @group = Group.find(params[:id])
    if !current_user.group_admins.find_by_group_id(@group.id) then
      redirect_to(groups_url :notice => 'You are not a admin of this group.')
    end
  end
  
end 

app/controllers/membership_requests_controller.rb
class MembershipRequestsController < ApplicationController
  def create
    @group = Group.find_by_id(params[:group_id])
    @request = @group.membership_requests.build(:user_id => current_user.id)
    @request.save
    redirect_to groups_path
  end

  def accept
    @group = Group.find_by_id(params[:group_id])
    @request = @group.membership_requests.find(params[:id])
    @request.accepted = true
    @request.save
    @group.users << User.find_by_id(@request.user_id)
    redirect_to group_path(params[:group_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Owner</th>
    <th></th>
    <th></th>
	<th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= group.description %></td>
    <td><%= User.find_by_id(group.owner_id).email %></td>

    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, :confirm => 'Are you sure?', :method => :delete %></td>
	<td><%= link_to 'Apply to group', group_membership_requests_path(group), :method => :post %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Description:</b>
  <%= @group.description %>
</p>

<p>
  <b>Owner:</b>
  <%= @owner.email%>
</p>

<p>
  <b>Members:</b><br>
  <% @group.users.each do |user|%>
  Email: <%=user.email%><br>
  <%end%>
</p>

<p>
  <b>Membership requests:</b><br>
  <% @group.membership_requests.each do |request|%>
  <% if !request.accepted then %>
  <%= User.find_by_id(request.user_id).email %>
  <%= link_to 'Accept', accept_group_membership_request_path(@group, request), :method => :post%>
  <%end%>
  <%end%>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groups</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div >  
  <% if user_signed_in? %>  
    Zalogowany jako: <%= current_user.email %> 
    <%= link_to "Wyloguj", destroy_user_session_path %>  
  <% else %>  
    <%= link_to "Zarejestruj", new_user_registration_path %> lub 
    <%= link_to "Zaloguj", new_user_session_path %>  
  <% end %>  
  <br>
</div>  
<%= yield %>

</body>
</html>